# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
